### ISSUE TITLE
Update Readme

### ISSUE THREAD

**Issue by MarkH817** [MarkH817/generator-lionbyte#41]
Before you submit an issue:
- Check for similar issues
- Provide error messages, if applicable
- Feature requests/suggestions are always welcome for discussion
- Title the issue appropriately

## Description
Reorganize feature section to be easier to read.
Add server project type to list

**Comment by sriikanth** [comment]
@MarkH817 Is the issue still open?
Shall i take it?

**Comment by MarkH817** [comment]
@sriikanth Go ahead! Thanks!
